"""Additive schema migration for SQLite.

    python -m scripts.migrate            # apply
    python -m scripts.migrate --dry-run  # show what would change

`Base.metadata.create_all` creates missing tables but never alters existing ones,
so adding a column to a model leaves the live database behind and every query
against that table fails. This walks the model metadata, compares it with the
live schema, creates missing tables and adds missing columns.

It is deliberately additive only: it will not drop or retype a column, because
doing that safely in SQLite means rebuilding the table and this is not the tool
to be doing that silently. Alembic is the production answer; this keeps a
fast-moving schema and 18 months of generated data in step without a full
rebuild each time.

The one exception is REBUILDABLE below — tables whose entire contents are
regenerated by a datagen module on every run. A constraint change on those is
safe to apply by dropping and recreating the table, because there is no data to
lose. Each entry has to be justified: if a table ever stops being fully
regenerated, it must come off this list.
"""

from __future__ import annotations

import argparse

from sqlalchemy import inspect, text
from sqlalchemy.schema import CreateIndex, CreateTable

from db.base import Base
from db.session import IS_SQLITE, engine
import db.models  # noqa: F401  (registers the models on Base.metadata)


# Tables regenerated in full by a datagen module, where a changed constraint can
# be applied by recreating the table rather than by leaving the database and the
# model silently disagreeing.
#
#   donation_test — rewritten by datagen.operations on every run. Its unique key
#   gained test_group, so a screening ELISA and its confirmatory RIBA for the
#   same marker can coexist; under the old key the confirmation collided with
#   the screen and the run failed.
REBUILDABLE = {"donation_test"}


def constraint_signature(connection, table_name: str) -> str:
    """The live table's DDL, for comparing against what the model now wants."""

    row = connection.execute(
        text("SELECT sql FROM sqlite_master WHERE type='table' AND name = :name"),
        {"name": table_name},
    ).fetchone()

    return (row[0] or "") if row else ""


def column_ddl_type(column) -> str:
    return column.type.compile(dialect=engine.dialect)


def default_clause(column) -> str:
    """Only literal defaults can be expressed in ALTER TABLE ADD COLUMN.

    Python-side defaults (a uuid factory, utcnow) are applied on insert by
    SQLAlchemy, so an added column simply starts NULL for existing rows, which is
    correct: we have no basis to invent a value for history.
    """

    default = column.default

    if default is None or default.is_callable or not default.is_scalar:
        return ""

    value = default.arg

    if isinstance(value, bool):
        return f" DEFAULT {1 if value else 0}"

    if isinstance(value, (int, float)):
        return f" DEFAULT {value}"

    if isinstance(value, str):
        escaped = value.replace("'", "''")
        return f" DEFAULT '{escaped}'"

    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply additive schema changes.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true")
    mode.add_argument(
        "--check",
        action="store_true",
        help="Report drift and exit non-zero without changing the database.",
    )
    args = parser.parse_args()
    preview = args.dry_run or args.check

    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())

    created_tables: list[str] = []
    added_columns: list[str] = []
    rebuilt_tables: list[str] = []

    with engine.begin() as connection:
        # SQLite will not add a column while foreign keys are being enforced on a
        # table that other tables reference.
        if IS_SQLITE:
            connection.exec_driver_sql("PRAGMA foreign_keys=OFF")

        for table in Base.metadata.sorted_tables:
            # A rebuildable table whose live constraints no longer match the
            # model gets recreated. Everything else is additive only.
            if IS_SQLITE and table.name in REBUILDABLE and table.name in existing_tables:
                wanted = str(CreateTable(table).compile(engine))
                live = constraint_signature(connection, table.name)

                def unique_keys(ddl: str) -> set:
                    import re

                    return {
                        tuple(part.strip() for part in match.split(","))
                        for match in re.findall(r"UNIQUE \(([^)]*)\)", ddl)
                    }

                if unique_keys(wanted) != unique_keys(live):
                    rebuilt_tables.append(table.name)

                    if not preview:
                        connection.exec_driver_sql(f"DROP TABLE {table.name}")
                        connection.execute(CreateTable(table))

                        for index in table.indexes:
                            connection.execute(CreateIndex(index))

                    continue

            if table.name not in existing_tables:
                created_tables.append(table.name)

                if not preview:
                    connection.execute(CreateTable(table))

                    for index in table.indexes:
                        connection.execute(CreateIndex(index))

                continue

            live_columns = {
                column["name"] for column in inspector.get_columns(table.name)
            }

            for column in table.columns:
                if column.name in live_columns:
                    continue

                added_columns.append(f"{table.name}.{column.name}")

                if preview:
                    continue

                statement = (
                    f'ALTER TABLE "{table.name}" '
                    f'ADD COLUMN "{column.name}" {column_ddl_type(column)}'
                    f"{default_clause(column)}"
                )
                connection.execute(text(statement))

            # Indexes declared on a model but absent from the live table.
            live_indexes = {
                index["name"] for index in inspector.get_indexes(table.name)
            }

            for index in table.indexes:
                if index.name in live_indexes:
                    continue

                if any(
                    column.name not in live_columns and column.name
                    not in {c.name for c in table.columns}
                    for column in index.columns
                ):
                    continue

                if not preview:
                    try:
                        connection.execute(CreateIndex(index))
                    except Exception as exc:  # pragma: no cover
                        print(f"  ! index {index.name}: {exc}")

        if IS_SQLITE:
            connection.exec_driver_sql("PRAGMA foreign_keys=ON")

    verb = "would create" if preview else "created"

    if created_tables:
        print(f"Tables {verb}: {len(created_tables)}")
        for name in created_tables:
            print(f"  + {name}")
    else:
        print("Tables: up to date")

    if rebuilt_tables:
        verb = "would rebuild" if preview else "rebuilt"
        print(f"Tables {verb} for a constraint change: {len(rebuilt_tables)}")
        for name in rebuilt_tables:
            print(f"  ~ {name}  (contents are regenerated, so nothing is lost)")

    verb = "would add" if preview else "added"

    if added_columns:
        print(f"Columns {verb}: {len(added_columns)}")
        for name in added_columns:
            print(f"  + {name}")
    else:
        print("Columns: up to date")

    drifted = bool(created_tables or rebuilt_tables or added_columns)

    if args.check and drifted:
        print("Schema check: migration required")
        return 1

    if args.check:
        print("Schema check: ready")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
