[theme]
primaryColor = "#B3122B"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false